version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/admin-migrations

    steps:
      - checkout
      - run:
          name: run apt-get
          command: |
            sudo apt-get update -y --quiet
            sudo apt-get install bc -y --quiet
      - run:
          name: migrate rerender and automerge
          command: |
            git config --global user.email "conda-forge-admin@email.com"
            git config --global user.name "conda-forge-admin"
            cd ..
            ./admin-migrations/scripts/migrate_rerender.sh

workflows:
  version: 2
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "5 * * * *"
          filters:
            branches:
              only:
                - master
