version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/admin-migrations

    steps:
      - checkout
      - run:
          name: run apt-get
          command: |
            sudo apt-get update
            sudo apt-get install bc
      - run:
          name: migrate rerender and automerge
          command: |
            cd ..
            ./admin-migrations/scripts/migrate_rerender.sh

workflows:
  version: 2
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
