name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - name: generate token
        id: generate_token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1
        with:
          app-id: ${{ secrets.CF_CURATOR_APP_ID }}
          private-key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73 # pin@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v2

      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v2
        with:
          python-version: 3.8
          channels: conda-forge
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          mamba install --quiet pip

          mamba install -y -q --file requirements.txt

          pip install --no-deps -e .

          git config --global user.email "79913779+conda-forge-curator[bot]@users.noreply.github.com"
          git config --global user.name "conda-forge-curator[bot]"
          git config --global pull.rebase false

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 admin_migrations

      - name: test
        shell: bash -l {0}
        run: |
          mkdir -p ~/.conda-smithy
          echo ${STAGING_BINSTAR_TOKEN} > ~/.conda-smithy/anaconda.token
          echo ${CIRCLE_TOKEN} > ~/.conda-smithy/circle.token
          echo ${TRAVIS_TOKEN_B} > ~/.conda-smithy/travis.token
          echo ${AZURE_TOKEN} > ~/.conda-smithy/azure.token
          echo ${DRONE_TOKEN} > ~/.conda-smithy/drone.token
          echo ${GITHUB_TOKEN} > ~/.conda-smithy/github.token

          export DEBUG_ADMIN_MIGRATIONS=1
          source ./scripts/clone_feedstock_outputs.sh
          run-admin-migrations
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
          TRAVIS_TOKEN_A: ${{ secrets.CF_LINTER_TRAVIS_TOKEN }}
          TRAVIS_TOKEN_B: ${{ secrets.CF_DAEMON_TRAVIS_TOKEN }}
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
          STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
